### ISSUE TITLE
firefox support

### ISSUE THREAD

**Issue by edsu** [tomayac/wikipedia-irc#3]
Perhaps I didn't wait long enough, but it doesn't look like the app works on Firefox 20.0. On the WebConsole I see a SecurityError (screenshot attahed) coming from within socket.io. I have seen socket.io working fine on other platforms FWIW, e.g http://wikistream.inkdroid.org 
![Screen Shot 2013-04-23 at 4 09 18 AM](https://f.cloud.github.com/assets/33829/413312/56ea7238-abed-11e2-9605-ce6983d19419.png)

**Comment by tomayac** [comment]
I can't reproduce this on my side, Ed. See the attached screenshot. This is Firefox 20.0 (release channel) on Mac OS X. Carefully closing this issue for now. Feel free to re-open if this is still an issue. 

![screen shot 2013-05-06 at 15 11 33](https://f.cloud.github.com/assets/145676/466040/8baf4c26-b64e-11e2-98af-026a717b9f8f.png)

**Comment by bymerej** [comment]
Did you try with HTTPS ?

That seems to make a difference for me.

Debian Wheezy. Mozilla/5.0 (X11; Linux x86_64; rv:20.0) Gecko/20100101 Firefox/20.0 Iceweasel/20.0

**Comment by tomayac** [comment]
> Did you try with HTTPS ?
> I didn't, but can indeed reproduce this now.

This seems to trigger something like a mixed-content security error,
as the app tries to connect as follows:

```
var socket = io.connect('http://wikipedia-irc.herokuapp.com/');
```

I don't know socket.io in detail, but is there a better way to catch a
connection error than try and catch?

```
var socket;
try {
  // use http
  socket = io.connect('http://wikipedia-irc.herokuapp.com/');
catch(e) {
  // use https
  socket = io.connect('https://wikipedia-irc.herokuapp.com/');
}
```

Would this work at all? Or should I connect to https from the beginning?

**Comment by bymerej** [comment]
you could copy the Google Analytics approach:
('https:' == document.location.protocol ? 'https://ssl' : 'http://www')

**Comment by tomayac** [comment]
('https:' == document.location.protocol ? 'https://ssl' : 'http://www')

Perfect :-) Thanks for the help!

**Comment by tomayac** [comment]
Deployed and confirmed working :-) Thanks again!
