### ISSUE TITLE
Detect edits by same editors across different wikipedias

### ISSUE THREAD

**Issue by nicolas-raoul** [tomayac/wikipedia-irc#4]
Checking one of the links that appeared in "Article Clusters Repeatedly Edited In Short Intervals", I noticed that it was not caused by a current event.
It was just a single user who decided to add a link on a city article, in many different languages.

This kind of editing behavior is sometimes by spammer, sometimes by normal users, but anyway it is usually not about a current event.

Maybe checking the author (or its IP if unregistered, or even the change's content) might help filter out this kind of non-events?

Cheers for the great tool, by the way, and for making it open source!

**Comment by tomayac** [comment]
Please note, the "Article Clusters Repeatedly Edited In Short Intervals" section does _not_ refer to breaking news candidates. The condition for actual breaking news candidates requires at least two independent editors. Only article clusters that fullfil all breaking news conditions are eventually displayed in the last section "Breaking News Candidate Article Clusters Right Now".
